# install.packages("librarian")

librarian::shelf(broom       ,
                 broom.mixed ,
                 car         ,
                 coxme       ,
                 devtools    ,
                 DHARMa      ,
                 flextable   ,
                 forcats     ,
                 geosphere   ,
                 ggeffects   ,
                 ggpubr      ,
                 glmmTMB     ,
                 grid        ,
                 here        ,
                 Hmisc       ,
                 knitr       ,
                 lme4        ,
                 lmerTest    ,
                 lsmeans     ,
                 MASS        ,
                 magrittr    ,
                 multcomp    ,
                 MuMIn       ,
                 nlme        ,
                 officer     ,
                 pbkrtest    ,
                 plyr        ,
                 png         ,
                 purrr       ,
                 scales      ,
                 stringi     ,
                 survival    ,
                 tidyverse   ,
                 vctrs       ,
                 vegan
                 )
  
library("tibble", lib.loc="~/R/win-library/3.5") 
