---
title: "Pop_and_Fam_Means"
output: html_document
---

1/2022: Import data first.

# Find family & population means
## reproductive
### Binary: flowering success
```{r}

# Find family means
flowered2020_familymeans <- reproductive  %>%
  dplyr::select(., c(2:7, 10, 14, 16:18)) %>%
  group_by(Population, Family) %>%
    dplyr::summarise(
      sum_replicates = n_distinct(Replicate),
      sum_flowered_indivs = sum(as.integer(Flowered2020)),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score),
      nPlants=n())


# Find population means
flowered2020_popmeans <- flowered2020_familymeans %>%
  group_by(Population) %>%
    dplyr::summarise(
      sum_replicates = sum(sum_replicates),
      sum_flowered_indivs = sum(as.integer(sum_flowered_indivs)),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score)) %>%
  as.data.frame(flowered2020_popmeans) %>%
  
# add percent flowered column
  dplyr::mutate(., percent_flowered = sum_flowered_indivs / sum_replicates)

# remove pops with only 1 rep?




# Use SummarySE to get stats per family & population

### NOT TRANSFORMED
# SSE_fams_height_2020 <- summarySE(DC7_2020_heights, measurevar="Total_Height", groupvars=c("Population", "Family"), na.rm=TRUE)
# SSE_fams_height_2020 <- merge(x = SSE_fams_height_2020, y = Distances, by = "Population", all.x = TRUE)
# 
# SSE_pops_height_2020 <- summarySE(SSE_fams_height_2020, measurevar="Total_Height", groupvars=c("Population"), na.rm=TRUE)
# ## removing pops with only 1 representative (4 pops)
# SSE_pops_height_2020 <- merge(x = SSE_pops_height_2020 %>% filter(N > 1), y = Distances, by = "Population", all.x = TRUE)


```



## Height
### 2019
```{r}

# Find family means
heights_both2019_familymeans <- heights_2019 %>%
  group_by(Population, Family) %>%
    dplyr::summarise(
      sum_replicates = n_distinct(Replicate),
      sum_height_earlyJune = sum(Total_Height_DC1),
      sum_height_midJune = sum(Total_Height_midJune),
      sum_height_Sept = sum(Total_Height_Sept),
      mean_Ramets_earlyJune = mean(Num_Ramets_DC1),
      mean_Ramets_midJune = mean(Ramets_midJune),
      mean_Ramets_Sept = mean(Ramets_Sept),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      mean_rel_growth_rate = mean(rel_growth_rate, na.rm = TRUE),
      Urb_score = first(Urb_score),
      nPlants=n())
## divide total height by num. plants/pop
heights_both2019_familymeans$mean_height_midJune <- heights_both2019_familymeans$sum_height_midJune / heights_both2019_familymeans$sum_replicates

heights_both2019_familymeans$mean_height_earlyJune <- heights_both2019_familymeans$sum_height_earlyJune / heights_both2019_familymeans$sum_replicates

heights_both2019_familymeans$mean_height_Sept <- heights_both2019_familymeans$sum_height_Sept / heights_both2019_familymeans$sum_replicates


# Find population means
heights_both2019_popmeans <- heights_both2019_familymeans %>%
  group_by(Population) %>%
    dplyr::summarise(
      sum_replicates = sum(sum_replicates),
      sum_height_earlyJune = sum(sum_height_earlyJune),
      sum_height_midJune = sum(sum_height_midJune),
      sum_height_Sept = sum(sum_height_Sept),
      mean_Ramets_earlyJune = mean(mean_Ramets_earlyJune),
      mean_Ramets_midJune = mean(mean_Ramets_midJune),
      mean_Ramets_Sept = mean(mean_Ramets_Sept),
      mean_height_earlyJune = mean(mean_height_earlyJune),
      mean_height_midJune = mean(mean_height_midJune),
      mean_height_Sept = mean(mean_height_Sept),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score),
      mean_rel_growth_rate = mean(mean_rel_growth_rate))


```



### 2020
```{r}

# Find family means
heights_both2020_familymeans <- heights_both_2020 %>%
  group_by(Population, Family) %>%
    dplyr::summarise(
      sum_replicates = n_distinct(Replicate),
      sum_height_June = sum(Total_Height_June),
      sum_height_Sept = sum(Total_Height_Sept),
      mean_Ramets_June = mean(Ramets_June),
      mean_Ramets_Sept = mean(Ramets_Sept),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      mean_rel_growth_rate = mean(rel_growth_rate),
      Urb_score = first(Urb_score),
      nPlants=n())
## divide total height by num. plants/pop
heights_both2020_familymeans$mean_height_June <- heights_both2020_familymeans$sum_height_June / heights_both2020_familymeans$sum_replicates

heights_both2020_familymeans$mean_height_Sept <- heights_both2020_familymeans$sum_height_Sept / heights_both2020_familymeans$sum_replicates


# Find population means
heights_both2020_popmeans <- heights_both2020_familymeans %>%
  group_by(Population) %>%
    dplyr::summarise(
      sum_replicates = sum(sum_replicates),
      sum_height_June = sum(sum_height_June),
      sum_height_Sept = sum(sum_height_Sept),
      mean_Ramets_June = mean(mean_Ramets_June),
      mean_Ramets_Sept = mean(mean_Ramets_Sept),
      mean_height_June = mean(mean_height_June),
      mean_height_Sept = mean(mean_height_Sept),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score),
      mean_rel_growth_rate = mean(mean_rel_growth_rate))



# # Use SummarySE to get stats per family & population
# ## HEIGHTS
# intermediate1 <- summarySE(heights_both_2020, measurevar="Total_Height_June", groupvars=c("Population", "Family"), na.rm=TRUE)
# 
# intermediate2 <- summarySE(heights_both_2020, measurevar="Total_Height_Sept", groupvars=c("Population", "Family"), na.rm=TRUE)
# 
# heights_2020_familymeans_stats <- left_join(intermediate1, intermediate2, by = c("Population", "Family"), suffix = c(".July", ".Sept"))
# 
# 
# # Use SummarySE to get stats per family & population
# ## no. ramets
# intermediate1 <- summarySE(heights_both_2020, measurevar="Ramets_June", groupvars=c("Population", "Family"), na.rm=TRUE)
# 
# intermediate2 <- summarySE(heights_both_2020, measurevar="Ramets_Sept", groupvars=c("Population", "Family"), na.rm=TRUE)
# 
# ramets_2020_familymeans_stats <- left_join(intermediate1, intermediate2, by = c("Population", "Family"), suffix = c(".June", ".Sept"))
# 
# # Add transect data via merge
# ramets_2020_familymeans_stats <- merge(ramets_2020_familymeans_stats, Distances, by = "Population", all.x = TRUE)
# 
# 
# 
# # SSE_pops_height_2020 <- summarySE(intermediates, measurevar="Total_Height", groupvars=c("Population"), na.rm=TRUE)

```


## Weevil scar lengths
```{r}
# Find family means
weevil_both2020_familymeans <- weevil_both %>%
  group_by(Population, Family) %>%
    dplyr::summarise(
      sum_replicates = n_distinct(Replicate),
      mean_scar_div_Juneheight = mean(scar_div_Juneheight, na.rm = TRUE),
      mean_scar = mean(Scar_length_cm),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score),
      nPlants=n())


# Find population means
weevil_both2020_popmeans <- weevil_both2020_familymeans %>%
  group_by(Population) %>%
    dplyr::summarise(
      sum_replicates = sum(sum_replicates),
      mean_scar_div_Juneheight = mean(mean_scar_div_Juneheight, na.rm = TRUE),
      mean_scar = mean(mean_scar),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score))



# Use SummarySE to get stats per family & population

### NOT TRANSFORMED
# SSE_fams_height_2020 <- summarySE(DC7_2020_heights, measurevar="Total_Height", groupvars=c("Population", "Family"), na.rm=TRUE)
# SSE_fams_height_2020 <- merge(x = SSE_fams_height_2020, y = Distances, by = "Population", all.x = TRUE)
# 
# SSE_pops_height_2020 <- summarySE(SSE_fams_height_2020, measurevar="Total_Height", groupvars=c("Population"), na.rm=TRUE)
# ## removing pops with only 1 representative (4 pops)
# SSE_pops_height_2020 <- merge(x = SSE_pops_height_2020 %>% filter(N > 1), y = Distances, by = "Population", all.x = TRUE)


```
## Herbivory
### 2019
```{r}
# Find family means
herbivory2019_familymeans <- herb_2019 %>%
  group_by(Population, Family) %>%
    dplyr::summarise(
      sum_replicates = n_distinct(Replicate),
      Herbivory.Sept_mean = mean(Herbivory_mean_Sept, na.rm = T),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score),
      nPlants=n())
herbivory2019_familymeans <- as.data.frame(herbivory2019_familymeans)


# Find population means
herbivory2019_popmeans <- herbivory2019_familymeans %>%
  group_by(Population) %>%
    dplyr::summarise(
      sum_replicates = sum(sum_replicates),
      Herbivory.Sept_mean = mean(Herbivory.Sept_mean, na.rm = T),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score))
herbivory2019_popmeans <- as.data.frame(herbivory2019_popmeans)

```

### 2020
```{r}
# Find family means
herbivory2020_familymeans <- herbivory_both_2020 %>%
  group_by(Population, Family) %>%
    dplyr::summarise(
      sum_replicates = n_distinct(Replicate),
      Herbivory.July_mean = mean(Herbivory.July_mean, na.rm = T),
      Herbivory.Sept_mean = mean(Herbivory.Sept_mean, na.rm = T),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score),
      nPlants=n())
herbivory2020_familymeans <- as.data.frame(herbivory2020_familymeans)


# Find population means
herbivory2020_popmeans <- herbivory2020_familymeans %>%
  group_by(Population) %>%
    dplyr::summarise(
      sum_replicates = sum(sum_replicates),
      Herbivory.July_mean = mean(Herbivory.July_mean, na.rm = T),
      Herbivory.Sept_mean = mean(Herbivory.Sept_mean, na.rm = T),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score))
herbivory2020_popmeans <- as.data.frame(herbivory2020_popmeans)


# Use SummarySE to get stats per family & population

### NOT TRANSFORMED
# SSE_fams_height_2020 <- summarySE(DC7_2020_heights, measurevar="Total_Height", groupvars=c("Population", "Family"), na.rm=TRUE)
# SSE_fams_height_2020 <- merge(x = SSE_fams_height_2020, y = Distances, by = "Population", all.x = TRUE)
# 
# SSE_pops_height_2020 <- summarySE(SSE_fams_height_2020, measurevar="Total_Height", groupvars=c("Population"), na.rm=TRUE)
# ## removing pops with only 1 representative (4 pops)
# SSE_pops_height_2020 <- merge(x = SSE_pops_height_2020 %>% filter(N > 1), y = Distances, by = "Population", all.x = TRUE)


```


## Survival
### 2019
```{r}
# Find family means
survival2019_familymeans <- surv_2019 %>%
  group_by(Population, Family) %>%
    dplyr::summarise(
      sum_replicates = n_distinct(Replicate),
      survival_mean = mean(Dead, na.rm = T),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score),
      nPlants=n())
survival2019_familymeans <- as.data.frame(survival2019_familymeans)


# Find population means
survival2019_popmeans <- survival2019_familymeans %>%
  group_by(Population) %>%
    dplyr::summarise(
      sum_replicates = sum(sum_replicates),
      survival_mean = mean(survival_mean, na.rm = T),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score))
survival2019_popmeans <- as.data.frame(survival2019_popmeans)

```


### 2020
```{r}
# Find family means
survival2020_familymeans <- survival_2020 %>%
  group_by(Population, Family) %>%
    dplyr::summarise(
      sum_replicates = n_distinct(Replicate),
      survival_mean = mean(dead_2020, na.rm = T),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score),
      nPlants=n())
survival2020_familymeans <- as.data.frame(survival2020_familymeans)


# Find population means
survival2020_popmeans <- survival2020_familymeans %>%
  group_by(Population) %>%
    dplyr::summarise(
      sum_replicates = sum(sum_replicates),
      survival_mean = mean(survival_mean, na.rm = T),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score))
survival2020_popmeans <- as.data.frame(survival2020_popmeans)


# Use SummarySE to get stats per family & population

### NOT TRANSFORMED
# SSE_fams_height_2020 <- summarySE(DC7_2020_heights, measurevar="Total_Height", groupvars=c("Population", "Family"), na.rm=TRUE)
# SSE_fams_height_2020 <- merge(x = SSE_fams_height_2020, y = Distances, by = "Population", all.x = TRUE)
# 
# SSE_pops_height_2020 <- summarySE(SSE_fams_height_2020, measurevar="Total_Height", groupvars=c("Population"), na.rm=TRUE)
# ## removing pops with only 1 representative (4 pops)
# SSE_pops_height_2020 <- merge(x = SSE_pops_height_2020 %>% filter(N > 1), y = Distances, by = "Population", all.x = TRUE)


```

## SLA & LDMC
```{r}
# Find family means
sla_ldmc2020_familymeans <- sla_ldmc %>%
  group_by(Population, Family) %>%
    dplyr::summarise(
      sum_replicates = n_distinct(Replicate),
      sla_mean = mean(SLA, na.rm = T),
      ldmc_mean = mean(LDMC, na.rm = T),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score),
      nPlants=n()) %>%
  as.data.frame()


# Find population means
sla_ldmc2020_popmeans <- sla_ldmc2020_familymeans %>%
  group_by(Population) %>%
    dplyr::summarise(
      sum_replicates = sum(sum_replicates),
      sla_mean = mean(sla_mean, na.rm = T),
      ldmc_mean = mean(ldmc_mean, na.rm = T),
      City_dist = first(City_dist),
      Transect_ID = first(Transect_ID),
      Urb_score = first(Urb_score)) %>%
  as.data.frame()


# Use SummarySE to get stats per family & population

### NOT TRANSFORMED
# SSE_fams_height_2020 <- summarySE(DC7_2020_heights, measurevar="Total_Height", groupvars=c("Population", "Family"), na.rm=TRUE)
# SSE_fams_height_2020 <- merge(x = SSE_fams_height_2020, y = Distances, by = "Population", all.x = TRUE)
# 
# SSE_pops_height_2020 <- summarySE(SSE_fams_height_2020, measurevar="Total_Height", groupvars=c("Population"), na.rm=TRUE)
# ## removing pops with only 1 representative (4 pops)
# SSE_pops_height_2020 <- merge(x = SSE_pops_height_2020 %>% filter(N > 1), y = Distances, by = "Population", all.x = TRUE)


```
