# Load libraries
```{r}
source(libraries.R)
```

# Import data
```{r}
sites <- read.csv(here::here("./data/CommonGardenExperiment_2019Data/clean_data/clean_haversine_Distances.csv"), sep = ",", header = TRUE) %>%
  dplyr::select(-X)


urb_scores <- read.csv(
  here::here("./CommonGardenExperiment_2020Data/raw_data/Urbanization_Score/Urbanization_Scores_Table.csv"),  header=T, na.strings=c("","NA")) %>%
  dplyr::select(Patch_ID, Urb_score, City_dist, Transect)


sites %<>% 
  dplyr::inner_join(.,
                    urb_scores,
                    by = c("Pop_ID" = "Patch_ID")) 

# add 2019 field data to extract populations whose seeds were actually planted
data_2019 <- read.csv(here::here("./data/CommonGardenExperiment_2019Data/clean_data/clean_data_2019KSR.csv"), sep = ",", header = TRUE) %>%
  dplyr::select(-X) 

# find number of pops per subtransect
data_2019 %>%
  dplyr::group_by( Transect_ID) %>%
  dplyr::summarise(pops = n_distinct(Population))

# keep only pops in above data_2019 vs all 80
sites %<>% 
  left_join(data_2019 %>%
             dplyr::group_by(Population) %>%
             dplyr::summarise(),
          .) %T>% view
```

# Map 1: Without urbanization scores shown
## Make large map
```{r}
# Make basemap of sampling sites-----
mylocation <- c(-80.19, 43.2, -79.2, 43.81)
base_map <- ggmap(get_map(location = mylocation,
                          maptype = 'terrain',
                          source = 'stamen'))
cols1 <- c("North" = "#FDE725FF",
           "South" = "#21908CFF", 
           "Rural" = "#660099")

map1 <- base_map +
  geom_point(data = sites,
             mapping = aes(x = Longitude, y = Latitude,
                           fill=Transect, shape=Transect),
             color = "black", size=3) +
  labs(x = 'Longitude', y = 'Latitude') +
  ggsn::scalebar(x.min = -80.19, x.max = -79.25,
           y.min = 43.25, y.max = 43.8,
           dist = 10, dist_unit = "km",
           st.bottom = FALSE, st.color = "black",
           transform = TRUE, model = 'WGS84',
           st.dist=.03) +
  theme(legend.position = c(0.75, 0.35),
        legend.background = element_rect(fill = "white",colour = "black"),
        legend.box.margin = margin(6, 6, 6, 6),
        legend.text = element_text(size=12),
        legend.title = element_text(size = 14),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14)) +
  scale_fill_manual(values = cols1,
                    breaks = c("North", "South", "Rural"),
                    labels = c("Urban: Non-Corridor", "Urban: Corridor", "Rural"),
                    name = "Sample Site Subtransect") +
  scale_shape_manual(values = c(23,24,21),
                     breaks = c("North", "South", "Rural"),
                     labels = c("Urban: Non-Corridor", "Urban: Corridor", "Rural"),
                     name = "Sample Site Subtransect") 


north2(map1, x = .59, y = .2, scale = 0.11, symbol = 1)



# widen and add KSR pin-----

KSR_point <- data.frame(long = 44.026961,
                        lat = -79.541771)

mylocation_wider <- c(-80.3, 43.2, -79.1, 44.1)
base_map_full <- ggmap(get_map(location = mylocation_wider,
                          maptype = 'terrain',
                          source = 'stamen'))


map1_wider <- base_map_full +
  geom_point(data = sites,
             mapping = aes(x = Longitude, y = Latitude,
                           fill=Transect, shape=Transect),
             color = "black", size=3) + 
  
  # Add KSR point
  geom_label_repel(data = KSR_point,
    aes(lat, long),
    label = "Koffler Scientific\n Reserve",
     nudge_x = 0.18,
     nudge_y = -0.08,
    size = 4 ,
    fontface = "italic",
    segment.color = 'gray'
   ) +
  
  geom_star(data = KSR_point, 
             mapping = aes(x = lat, y = long),
             color = "black", fill = "orangered",
             size = 5 ) +

  labs(x = 'Longitude', y = 'Latitude') +

  ggsn::scalebar(x.min = -80.3, x.max = -79.85,
           y.min = 44.05, y.max = 44.1,
           height = 0.4, st.dist= 0.5,
           dist = 15, dist_unit = "km",
           st.bottom = TRUE, st.color = "black",
           st.size = 4,
           transform = TRUE, model = 'WGS84'
           ) +
  theme(#legend.position = c(0.32, 0.65),
        legend.position = c(0.75, 0.15),
        legend.background = element_rect(fill = "white",colour = "black"),
        legend.box.margin = margin(4,4,4,4),
        legend.text = element_text(size=11),
        legend.title = element_text(size = 12),
        axis.text=element_text(size=12),
        axis.title=element_text(size=12)) +
  scale_fill_manual(values = cols1,
                    breaks = c("North", "South", "Rural"),
                    labels = c("Urban: Non-Corridor", "Urban: Corridor", "Rural"),
                    name = "Sample Site Subtransect") +
  scale_shape_manual(values = c(23,24,21),
                     breaks = c("North", "South", "Rural"),
                     labels = c("Urban: Non-Corridor", "Urban: Corridor", "Rural"),
                     name = "Sample Site Subtransect") 
 #map1_wider


ggsn::north2(map1_wider, x = .29, y = .8,
       scale = 0.11, symbol = 1)


# Export
dev.copy2pdf(file = here::here("./Figures_Tables/map/map_noinset.pdf"),
             width = 7, height = 5)
```

## Create inset of point in North America
```{r}

mylocation_inset <- c(-87, 40, -72, 47)
base_map_inset <- ggmap(get_map(location = mylocation_inset,
                          maptype = 'toner-background',
                          source = 'stamen',
                          color = "bw"),
                        darken = c(0.75, "white"))


map1_inset <- base_map_inset +
  
  # Add KSR point
  # geom_star(data = KSR_point, 
  #            mapping = aes(x = lat, y = long),
  #            color = "black", fill = "orangered",
  #            size = 7 ) +
  
  # Add rectangle of area
    geom_rect(aes(xmin = -80.3, xmax = -79.1,
                  ymin = 43.2, ymax = 44.1),
              color = "red", fill = NA)  +

  labs(x = 'Longitude', y = 'Latitude') +

  theme(legend.position = "none",
        axis.text=element_text(size=12),
        axis.title=element_text(size=12)) +
    theme_void() +
  theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1))
map1_inset


```

## Add inset to larger map
```{r}
# First, move scale bar and north arrow from larger map
map1_large <- base_map_full +
  geom_point(data = sites,
             mapping = aes(x = Longitude, y = Latitude,
                           fill=Transect, shape=Transect),
             color = "black", size=3) + 
  
  # Add KSR point
  geom_text_repel(data = KSR_point,
    aes(lat, long),
    label = "Koffler Scientific\n Reserve",
     nudge_x = 0.22,
     nudge_y = -0.02,
    size = 4 ,
    color = "gray18",
    fontface = "bold",
    segment.color = 'gray'
   ) +
  
    geom_star(data = KSR_point, 
             mapping = aes(x = lat, y = long),
             color = "gray26", fill = "forestgreen",
             size = 6.5) +
  
  # geom_point(data = KSR_point, 
  #            mapping = aes(x = lat, y = long),
  #            color = "black", fill = "dodgerblue",
  #            shape = 21,
  #            size = 6 ) +
  
  # # add extra "X" on top of point
  #   geom_point(data = KSR_point, 
  #            mapping = aes(x = lat, y = long),
  #            color = "black",
  #            shape = 8,
  #            size = 4 ) +

  labs(x = 'Longitude', y = 'Latitude') +

  ggsn::scalebar(x.min = -80.2, x.max = -79.8,
           y.min = 43.24, y.max = 43.28,
           height = 0.4, st.dist= 0.5,
           dist = 15, dist_unit = "km",
           st.bottom = TRUE, st.color = "black",
           st.size = 4,
           transform = TRUE, model = 'WGS84'
           ) +
  theme(#legend.position = c(0.32, 0.65),
        legend.position = c(0.75, 0.15),
        legend.background = element_rect(fill = "white",
                                         colour = "grey30",
                                         size = 0.15),
        legend.box.margin = margin(4,4,4,4),
        legend.text = element_text(size=11),
        legend.title = element_text(size = 12),
        axis.text=element_text(size=12),
        axis.title=element_text(size=12)) +
  scale_fill_manual(values = cols1,
                    breaks = c("North", "South", "Rural"),
                    labels = c("Urban: Non-Corridor", "Urban: Corridor", "Rural"),
                    name = "Sample Site Subtransect") +
  scale_shape_manual(values = c(23,24,21),
                     breaks = c("North", "South", "Rural"),
                     labels = c("Urban: Non-Corridor", "Urban: Corridor", "Rural"),
                     name = "Sample Site Subtransect") 

map1_large

# then add inset to larger map
full <- map1_large +
    ggmap::inset(ggplotGrob(map1_inset),
        xmin = -79.75,
        xmax = -80.25,
        ymin = 43.8,
        ymax = 44.1 
        ) 

ggsn::north2(full, 
         #    x = .29, y = .25,
             x = .26, y = .15,
       scale = 0.09, symbol = 3)



# Export
dev.copy2pdf(file = here::here("./Figures_Tables/map/map_inset.pdf"),
             width = 7, height = 5)

```

# Map 2: With urbanization scores shown
## Make large map
```{r}

map1 <- base_map +
  geom_point(data = sites,
             mapping = aes(x = Longitude, y = Latitude,
                           fill=Urb_score, shape=Transect),
             color = "black", size=3) +
  labs(x = 'Longitude', y = 'Latitude') +
  ggsn::scalebar(x.min = -80.19, x.max = -79.25,
           y.min = 43.25, y.max = 43.8,
           dist = 10, dist_unit = "km",
           st.bottom = FALSE, st.color = "black",
           transform = TRUE, model = 'WGS84',
           st.dist=.03) +
  theme(legend.position = c(0.75, 0.35),
        legend.background = element_rect(fill = "white",colour = "black"),
        legend.box.margin = margin(6, 6, 6, 6),
        legend.text = element_text(size=12),
        legend.title = element_text(size = 14),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14)) +
  scale_shape_manual(values = c(23,24,21),
                     breaks = c("North", "South", "Rural"),
                     labels = c("Urban: Non-Corridor", "Urban: Corridor", "Rural"),
                     name = "Sample Site Subtransect")  +
  scale_fill_gradient(low = "white", high = "dark red",
                      breaks=c(-4, -2, 0, 2, 4),
                      labels=c("-4 (Rural)", -2, 0, 2, "4 (Urban)"),
                      limits=c(-4, 4),
                      name = "Urbanization Score"
                      ) +
  guides(fill = guide_colorbar(title = "Urbanization Score",
                               # label.position = "top",
                               title.position = "top",
                               # title.vjust = 1,
                               # draw border around the legend
                               frame.colour = "black",
                               frame.linewidth = 1.5,
                               barwidth = 1,
                               barheight = 5)) 


north2(map1, x = .59, y = .2, scale = 0.11, symbol = 1)



# widen and add KSR pin-----
map1_wider <- base_map_full +
  geom_point(data = sites,
             mapping = aes(x = Longitude, y = Latitude,
                           fill=Urb_score, shape=Transect),
             color = "black", size=3) + 
  
  # Add KSR point
  geom_label_repel(data = KSR_point,
    aes(lat, long),
    label = "Koffler Scientific\n Reserve",
     nudge_x = 0.18,
     nudge_y = -0.08,
    size = 4 ,
    fontface = "italic",
    segment.color = 'gray'
   ) +
  
  geom_star(data = KSR_point, 
             mapping = aes(x = lat, y = long),
             color = "black", fill = "orangered",
             size = 5 ) +

  labs(x = 'Longitude', y = 'Latitude') +

  ggsn::scalebar(x.min = -80.3, x.max = -79.85,
           y.min = 44.05, y.max = 44.1,
           height = 0.4, st.dist= 0.5,
           dist = 15, dist_unit = "km",
           st.bottom = TRUE, st.color = "black",
           st.size = 4,
           transform = TRUE, model = 'WGS84'
           ) +
  theme(#legend.position = c(0.32, 0.65),
        legend.position = c(0.75, 0.15),
        legend.background = element_rect(fill = "white",colour = "black"),
        legend.box.margin = margin(4,4,4,4),
        legend.text = element_text(size=11),
        legend.title = element_text(size = 12),
        axis.text=element_text(size=12),
        axis.title=element_text(size=12)) +
   scale_shape_manual(values = c(23,24,21),
                     breaks = c("North", "South", "Rural"),
                     labels = c("Urban: Non-Corridor", "Urban: Corridor", "Rural"),
                     name = "Sample Site Subtransect")  +
  scale_fill_gradient(low = "white", high = "dark red",
                      breaks=c(-4, -2, 0, 2, 4),
                      labels=c("-4 (Rural)", -2, 0, 2, "4 (Urban)"),
                      limits=c(-4, 4),
                      name = "Urbanization Score"
                      ) +
  guides(fill = guide_colorbar(title = "Urbanization Score",
                               # label.position = "top",
                               title.position = "top",
                               # title.vjust = 1,
                               # draw border around the legend
                               frame.colour = "black",
                               frame.linewidth = 1.5,
                               barwidth = 1,
                               barheight = 5))
 map1_wider


ggsn::north2(map1_wider, x = .29, y = .8,
       scale = 0.11, symbol = 1)


# Export
dev.copy2pdf(file = here::here("./Figures_Tables/map/map_noinset_USC.pdf"),
             width = 7, height = 5)
```

## Add inset to larger map
```{r}
# First, move scale bar and north arrow from larger map
map1_large <- base_map_full +
  geom_point(data = sites,
             mapping = aes(x = Longitude, y = Latitude,
                           fill=Urb_score, shape=Transect),
             color = "black", size=3) + 
  
  # Add KSR point
  geom_text_repel(data = KSR_point,
    aes(lat, long),
    label = "Koffler Scientific\n Reserve",
     nudge_x = 0.22,
     nudge_y = -0.02,
    size = 4 ,
    color = "gray18",
    fontface = "bold",
    segment.color = 'gray'
   ) +
  
    geom_star(data = KSR_point, 
             mapping = aes(x = lat, y = long),
             color = "gray26", fill = "forestgreen",
             size = 6.5) +
  
  labs(x = 'Longitude', y = 'Latitude') +

  ggsn::scalebar(x.min = -80.2, x.max = -79.8,
           y.min = 43.24, y.max = 43.28,
           height = 0.4, st.dist= 0.5,
           dist = 15, dist_unit = "km",
           st.bottom = TRUE, st.color = "black",
           st.size = 4,
           transform = TRUE, model = 'WGS84'
           ) +
  theme(legend.position = c(0.24, 0.68),
        legend.background = element_rect(fill = "white",
                                         colour = "grey30"),
        legend.box.margin = margin(0,0,0,0),
        legend.text = element_text(size=10.5),
        legend.title = element_text(size = 11),
        axis.text=element_text(size=12),
        axis.title=element_text(size=12)) +
   scale_shape_manual(values = c(23,24,21),
                     breaks = c("North", "South", "Rural"),
                     labels = c("Urban: Non-Corridor", "Urban: Corridor", "Rural"),
                     name = "Sample Site Subtransect")  +
  scale_fill_gradient(low = "white", high = "dark red",
                      breaks=c(-4, -2, 0, 2, 4),
                      labels=c("-4 (Rural)", -2, 0, 2, "4 (Urban)"),
                      limits=c(-4, 4),
                      name = "Urbanization Score"
                      ) +
  guides(fill = guide_colorbar(title = "Urbanization Score",
                               # label.position = "top",
                               title.position = "top",
                               # title.vjust = 1,
                               # draw border around the legend
                               frame.colour = "black",
                               frame.linewidth = 1.5,
                               barwidth = 1,
                               barheight = 5)) + 
  guides(shape = guide_legend(order = 2),
         col = guide_legend(order = 1))

map1_large

# then add inset to larger map
full <- map1_large +
    ggmap::inset(ggplotGrob(map1_inset),
        # xmin = -79.75,
        # xmax = -80.25,
        # ymin = 43.8,
        # ymax = 44.1 
        xmin = -79.15,
        xmax = -79.65,
        ymin = 43.5,
        ymax = 43.22 
        ) 

ggsn::north2(full, 
         #    x = .29, y = .25,
             x = .26, y = .15,
       scale = 0.09, symbol = 3)



# Export
dev.copy2pdf(file = here::here("./Figures_Tables/map/map_inset_USC.pdf"),
             width = 7, height = 5)

```
