---
title: "Cardenolide Analysis (KSR 2020)"
author: "Sophie Breitbart"
output:
  html_document:
    number_sections: false
    df_print: paged
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
editor_options: 
  chunk_output_type: console
---

# Set up notebook
## Load libraries and add functions

```{r}
source("libraries.R")
source("functions.R")
```

## Import data
```{r}
# cardenolides per population (pooled)
cards <-  read.csv(here::here("./CommonGardenExperiment_2020Data/clean_data/2020_cardenolides_clean.csv")) %>%
  dplyr::select(., -1) 
```

# Diagnostics + anova
## Get names of response variables
```{r}
cards_vars <- cards %>%
  dplyr::select(3,5,7,10) %>%
  names() %>%
  as.list()
```

## Predictor: City_dist
```{r}
city_dist_list <- lapply(cards_vars,
       DoLinearReg,
       predictor_var = "City_dist",
       input_data = cards)
names(city_dist_list) <- cards_vars
# Num 3 doesn't look normal... try transformation. Residuals look bimodal

# I don't think I should do this analysis because there are only 35 urban populations: 17 non-corridor and 18 corridor
city_dist_list2 <- lapply(cards_vars,
       DoLinearReg,
       predictor_var = "City_dist * Transect_ID",
       input_data = cards %>% dplyr::filter(Transect_ID != "Rural"))
names(city_dist_list2) <- cards_vars
# looks fine
```

## Investigate non-normal-looking models
```{r}
DoLinearReg("X17.6_main", "City_dist", cards)
DoLinearReg("log(X17.6_main)", "City_dist", cards)
car::Anova(lm(log(X17.6_main) ~ City_dist, cards)) # still isn't near p = 0.05 so maybe not worth worrying about
```

## Predictor: Urb_score
```{r}
urb_score_list <- lapply(cards_vars,
       DoLinearReg,
       predictor_var = "Urb_score",
       input_data = cards)
names(urb_score_list) <- cards_vars
# Num 3 doesn't look normal... try transformation. Looks bimodal
```

## Investigate non-normal-looking models
```{r}
DoLinearReg("X17.6_main", "Urb_score", cards)
DoLinearReg("log(X17.6_main)", "Urb_score", cards) # looks better
car::Anova(lm(log(X17.6_main) ~ Urb_score, cards))

urb_score_list[[3]] <- DoLinearReg("log(X17.6_main)", "Urb_score", cards)
```

# R-squared values
## City_dist
```{r}
# 6.6
city_dist_list[[1]][[1]] %>%
  performance::model_performance() %>%
  as.data.frame() %>%
  dplyr::select(c(3:4))

# 15
city_dist_list[[2]][[1]] %>%
  performance::model_performance() %>%
  as.data.frame() %>%
  dplyr::select(c(3:4))

# 17.6
city_dist_list[[3]][[1]] %>%
  performance::model_performance() %>%
  as.data.frame() %>%
  dplyr::select(c(3:4))

# total
city_dist_list[[4]][[1]] %>%
  performance::model_performance() %>%
  as.data.frame() %>%
  dplyr::select(c(3:4))
```

## Urb_score
```{r}
# 6.6
urb_score_list[[1]][[1]] %>%
  performance::model_performance() %>%
  as.data.frame() %>%
  dplyr::select(c(3:4))

# 15
urb_score_list[[2]][[1]] %>%
  performance::model_performance() %>%
  as.data.frame() %>%
  dplyr::select(c(3:4))

# 17.6
urb_score_list[[3]][[1]] %>%
  performance::model_performance() %>%
  as.data.frame() %>%
  dplyr::select(c(3:4))

# total
urb_score_list[[4]][[1]] %>%
  performance::model_performance() %>%
  as.data.frame() %>%
  dplyr::select(c(3:4))
```


# Estimated marginal means
```{r}
# total cards
m1 <- lm(total ~ City_dist, cards)
summary(m1)
## estimate at x = 0 (urban terminus): mx + b = 0 + b = 0.358397
## estimate at x = 67 (rural terminus): (67)*(-0.001820) + 0.358397 = 0.236457
## percent change, rur to urb: 
#### percent_change <- ((urb_mean - rur_mean) / rur_mean) * 100
percent_change <- (((0.358397 - 0.236457) / 0.236457) * 100) %T>%
  print()


# peak 6.6
m2 <- lm(X6.6_main ~ City_dist, cards)
summary(m2)
## estimate at x = 0 (urban terminus): mx + b = 0 + b = 0.2619764  
## estimate at x = 67 (rural terminus): (67)*(-0.0015764) + 0.2619764 = 0.1563576
## percent change, rur to urb: 
#### percent_change <- ((urb_mean - rur_mean) / rur_mean) * 100
percent_change <- (((0.2619764 - 0.1563576) / 0.1563576) * 100) %T>%
  print()
```

# Heritability- not possible b/c no families within pops?
```{r}
# 6.6
mod_66 <- lm(X6.6_main ~ City_dist,
             data = cards,
             REML = T)

VarCorr(mod_66)

# residual variance:
resid_var <- update(
    herb_e_bin_mods_best_c[[1]], REML = T) %>%
    sigma()

Calc_h2_qst(1.4560e-04,
         1.5085e-05,
         resid_var)
```

