---
title: "Diagnostics"
author: "Sophie Breitbart"
date: "2/23/2022"
output: html_document
---
# LDMC
## Gradient
### City_dist
```{r}
ldmc_gr_city_m1 <- glmmTMB(LDMC ~ (1|Block) + (1|Population/Family) + City_dist,
                        data = sla_ldmc,
                        REML = F)

performance::check_model(ldmc_gr_city_m1) # looks like an outlier. Remove and try again

# performance::check_model(update(ldmc_gr_city_m1, . ~ . , data = sla_ldmc %>% dplyr::filter(LDMC < 1)))
# # convergence problem. Take out block

performance::check_model(update(ldmc_gr_city_m1, . ~ (1|Population/Family) + City_dist , data = sla_ldmc %>%
                                  dplyr::filter(LDMC < 1))) # better! put back outlier to see if it changes

# performance::check_model(update(ldmc_gr_city_m1, . ~ (1|Population/Family) + City_dist , data = sla_ldmc)) # still an outlier. Keep out. Still a bit right-skewed though, so try sqrt
# 
# performance::check_model(update(ldmc_gr_city_m1, sqrt(LDMC) ~ (1|Population/Family) + City_dist , data = sla_ldmc %>% dplyr::filter(LDMC < 1))) # convergence issue again. Stick with untransformed model


ldmc_gr_city_m1 <- glmmTMB(LDMC ~ (1|Population/Family) + City_dist,
                           data = sla_ldmc %>%
                             dplyr::filter(LDMC < 1.5))

car::Anova(ldmc_gr_city_m1)
# returning NaNs. Try making family unique and then crossing?

sla_ldmc %<>%
  dplyr::mutate(Fam_uniq = paste0(Population, "_", Family))

# this works: p = 0.19
car::Anova(update(ldmc_gr_city_m1,
                  . ~ (1|Population:Fam_uniq) + City_dist ,
                  data = sla_ldmc %>%
                    dplyr::filter(LDMC < 1)))

# gives same result (p = 0.19)
car::Anova(update(ldmc_gr_city_m1,
                             . ~ (1|Population:Family) + City_dist ,
                             data = sla_ldmc %>%
                               dplyr::filter(LDMC < 1)))

# this doesn't work though
car::Anova(update(ldmc_gr_city_m1,
                             . ~ (1|Population/Fam_uniq) + City_dist ,
                             data = sla_ldmc %>%
                               dplyr::filter(LDMC < 1)))

# this DOES work and gives same result as previous models
car::Anova(update(ldmc_gr_city_m1,
                             . ~ (1|Fam_uniq) + City_dist ,
                             data = sla_ldmc %>%
                               dplyr::filter(LDMC < 1)))


# going to use this as final model
ldmc_gr_city_m1 <- glmmTMB(LDMC ~ (1|Population:Fam_uniq) + City_dist,
                             data = sla_ldmc %>%
                               dplyr::filter(LDMC < 1))
car::Anova(ldmc_gr_city_m1)
performance::check_model(ldmc_gr_city_m1)
```

### Urb_score
```{r}
ldmc_gr_usc_m1 <- glmmTMB(LDMC ~ (1|Block) + (1|Population/Family) + Urb_score,
                        data = sla_ldmc,
                        REML = F)

performance::check_model(ldmc_gr_usc_m1) # remove same outlier

performance::check_model(update(ldmc_gr_usc_m1, . ~ . ,
                                data = sla_ldmc %>%
                                  dplyr::filter(LDMC < 1)))
# works fine

car::Anova(update(ldmc_gr_usc_m1, . ~ . ,
                                data = sla_ldmc %>%
                                  dplyr::filter(LDMC < 1)))

# I took out block: result barely changed. Subbed in Fam_uniq, result didn't change.


ldmc_gr_usc_m1 <- glmmTMB(LDMC ~ (1|Block) + (1|Population/Family) + Urb_score,
                        data = sla_ldmc %>%
                                  dplyr::filter(LDMC < 1),
                        REML = F)
```

## Urban Subtransects
### City_dist
```{r}
ldmc_urbsubs_city_m1 <- glmmTMB(LDMC ~ (1|Block) + (1|Population/Family) + City_dist,
                        data = sla_ldmc %>%
                          dplyr::filter(Transect_ID != "Rural"),
                        REML = F)

performance::check_model(ldmc_urbsubs_city_m1) # looks like an outlier. Remove and try again

performance::check_model(update(ldmc_urbsubs_city_m1, . ~ .,
                                data = sla_ldmc %>%
                                  dplyr::filter(Transect_ID != "Rural") %>%
                                  dplyr::filter(LDMC < 1.5))) # now it's not converging, based on exclusion of 1 point ? Try using Fam_uniq

# this works. As does using (1|Fam_uniq)
performance::check_model(update(ldmc_urbsubs_city_m1, . ~ (1|Block) + (1|Population:Fam_uniq) + City_dist,
                                data = sla_ldmc %>%
                                  dplyr::filter(Transect_ID != "Rural" & LDMC < 1.5)))


# gives same result as (1|Fam_uniq)
car::Anova(update(ldmc_urbsubs_city_m1, . ~ (1|Block) + (1|Population:Fam_uniq) + City_dist,
                                data = sla_ldmc %>%
                                  dplyr::filter(Transect_ID != "Rural" & LDMC < 1.5)))



ldmc_urbsubs_city_m1 <- glmmTMB(LDMC ~ (1|Block) + (1|Population:Fam_uniq) + City_dist,
                        data = sla_ldmc %>%
                                  dplyr::filter(Transect_ID != "Rural" & LDMC < 1.5),
                        REML = F)
```

### Urb_score
```{r}
ldmc_urbsubs_usc_m1 <- glmmTMB(LDMC ~ (1|Block) + (1|Population/Family) + Urb_score,
                        data = sla_ldmc %>%
                          dplyr::filter(Transect_ID != "Rural"),
                        REML = F)

performance::check_model(ldmc_urbsubs_usc_m1) # looks like an outlier. Remove and try again. Also not converging


performance::check_model(update(ldmc_urbsubs_usc_m1, . ~ .,
                                data = sla_ldmc %>%
                                  dplyr::filter(Transect_ID != "Rural" & LDMC < 1.5))) # now it's converging. But try using Fam_uniq

# this works. As does using (1|Fam_uniq)
performance::check_model(update(ldmc_urbsubs_usc_m1, . ~ (1|Block) + (1|Population:Fam_uniq) + Urb_score,
                                data = sla_ldmc %>%
                                  dplyr::filter(Transect_ID != "Rural" & LDMC < 1.5)))

# gives same result as (1|Fam_uniq)
car::Anova(update(ldmc_urbsubs_usc_m1, . ~ (1|Block) + (1|Population:Fam_uniq) + Urb_score,
                                data = sla_ldmc %>%
                                  dplyr::filter(Transect_ID != "Rural" & LDMC < 1.5)))

# this one gives slightly larger p-value (0.48 compared to 0.44). So it's qualitatively not different than above models, which I'll use to be consistent with other variable's diagnostics.
car::Anova(update(ldmc_urbsubs_usc_m1, . ~ .,
                                data = sla_ldmc %>%
                                  dplyr::filter(Transect_ID != "Rural") %>%
                                  dplyr::filter(LDMC < 1.5))) 


ldmc_urbsubs_usc_m1 <- glmmTMB(LDMC ~ (1|Block) + (1|Population:Fam_uniq) + Urb_score,
                                data = sla_ldmc %>%
                                  dplyr::filter(Transect_ID != "Rural" & LDMC < 1.5))

car::Anova(ldmc_urbsubs_usc_m1)
```

# LDMC
## Gradient
### City_dist
```{r}
sla_gr_city_m1 <- glmmTMB(SLA ~ (1|Block) + (1|Population/Family) + City_dist,
                        data = sla_ldmc,
                        REML = F)

performance::check_model(sla_gr_city_m1) 

# performance::check_model(update(ldmc_gr_city_m1, . ~ . , data = sla_ldmc %>% dplyr::filter(LDMC < 1)))
# # convergence problem. Take out block

```

### Urb_score
```{r}

```

## Urban Subtransects
### City_dist
```{r}

```

### Urb_score
```{r}

```


# Herbivory: September (post-flowering)
## Gradient
### City_dist
```{r}
herbivory_gr_dist_m1 <- glmer(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + (1|Population/Family) + City_dist,
                              data = herbivory_19_20,
                              family = "binomial"(link = "logit"),
                              control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

res <- simulateResiduals(herbivory_gr_dist_m1)
plot(res)
testDispersion(herbivory_gr_dist_m1)
# qqplot looks very off... try  ????
hist(herbivory_19_20$Herbivory_mean_Sept, breaks = 30)
summary(herbivory_gr_dist_m1)


herbivory_gr_dist_m2 <- glmer(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + (1|Family) + City_dist,
                              data = herbivory_19_20,
                              family = "binomial"(link = "logit"),
                              control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))
res <- simulateResiduals(herbivory_gr_dist_m2)
plot(res)

# try removing pop and making families unique
herbivory_19_20[,"FamPop"] <- paste0(herbivory_19_20$Family, "-", herbivory_19_20$Population)

herbivory_gr_dist_m3 <- glmer(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + City_dist,
                              data = herbivory_19_20,
                              family = "binomial"(link = "logit"),
                              control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

summary(herbivory_gr_dist_m3)
# trying to find where all the variance is being eaten up/accounted for and still not finding it... try beta distribution


herbivory_gr_dist_m4 <- glmmTMB(Herbivory_mean_Sept  ~ (1|Block) + (1|Year) + (1|Population/Family) + City_dist,
                                data = herbivory_19_20,
                                family = beta_family(link="logit"))
# Error in eval(family$initialize) : y values must be 0 < y < 1
# recode: 0s as 0.00001 & 1 as 0.999999

herbivory_19_20_recode <- herbivory_19_20
herbivory_19_20_recode$Herbivory_mean_Sept[herbivory_19_20_recode$Herbivory_mean_Sept == 1] <- 0.999999
herbivory_19_20_recode$Herbivory_mean_Sept[herbivory_19_20_recode$Herbivory_mean_Sept == 0] <- 0.000001



herbivory_gr_dist_m5 <- glmmTMB(Herbivory_mean_Sept  ~ (1|Block) + (1|Year) + (1|Population/Family) + City_dist,
                                data = herbivory_19_20_recode,
                                family = beta_family(link="logit"))
res <- simulateResiduals(herbivory_gr_dist_m5)
plot(res)
# IT WORKS

hist(herbivory_19_20$Herbivory_mean_Sept, breaks = 30)
summary(herbivory_gr_dist_m5)


herbivory_gr_dist_m6 <- glmmTMB(Herbivory_mean_Sept  ~ (1|Block) + Year + (1|Population/Family) + City_dist,
                                data = herbivory_19_20_recode,
                                family = beta_family(link="logit"))
res <- simulateResiduals(herbivory_gr_dist_m6)
plot(res)

herbivory_gr_dist_m7 <- glmmTMB(Herbivory_mean_Sept  ~ (1|Block) + Year + (1|FamPop) + City_dist,
                                data = herbivory_19_20_recode,
                                family = beta_family(link="logit"))
res <- simulateResiduals(herbivory_gr_dist_m7)
plot(res)

herbivory_gr_dist_m8 <- glmmTMB(Herbivory_mean_Sept  ~  Year + (1|FamPop) + City_dist,
                                data = herbivory_19_20_recode,
                                family = beta_family(link="logit"))
res <- simulateResiduals(herbivory_gr_dist_m8)
plot(res)

car::Anova(herbivory_gr_dist_m7) # doesn't run
car::Anova(herbivory_gr_dist_m8)
```

### Urb_score
```{r}
herbivory_gr_usc_m1 <- glmer(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + (1|Population/Family) + Urb_score,
                             data = herbivory_19_20,
                             family = binomial,
                             control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

res <- simulateResiduals(herbivory_gr_usc_m1)
plot(res)
# try beta

herbivory_gr_usc_m2 <- glmmTMB(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + (1|Population/Family) + Urb_score,
                               data = herbivory_19_20_recode,
                               family = beta_family(link="logit"))

res <- simulateResiduals(herbivory_gr_usc_m2)
plot(res)
```

## Urban Sites
### City_dist
```{r}
herbivory_urb_dist_m1 <- glmer(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + (1|Population/Family) + City_dist * Transect_ID,
                               data = herbivory_19_20 %>% dplyr::filter(., Transect_ID != "Rural"),
                               family = binomial,
                               control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

res <- simulateResiduals(herbivory_urb_dist_m1)
plot(res)
# try beta

herbivory_urb_dist_m2 <- glmmTMB(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + (1|Population/Family) + City_dist * Transect_ID,
                                 data = herbivory_19_20_recode %>% dplyr::filter(., Transect_ID != "Rural"),
                                 family = beta_family(link="logit"))

res <- simulateResiduals(herbivory_urb_dist_m2)
plot(res)


# main effects:
herbivory_urb_dist_m2_ME <- herbivory_urb_dist_m2 <- glmmTMB(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + (1|Population/Family) + City_dist + Transect_ID,
                                                             data = herbivory_19_20_recode %>% dplyr::filter(., Transect_ID != "Rural"),
                                                             family = beta_family(link="logit"))
```

### Urb_score
```{r}
herbivory_urb_usc_m1 <- glmer(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + (1|Population/Family) + Urb_score * Transect_ID,
                              data = herbivory_19_20 %>% dplyr::filter(., Transect_ID != "Rural"),
                              family = binomial,
                              control=glmerControl(optimizer="bobyqa", optCtrl=list(maxfun=2e5)))

res <- simulateResiduals(herbivory_urb_usc_m1)
plot(res)
# try beta

herbivory_urb_usc_m2 <- glmmTMB(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + (1|Population/Family) + Urb_score * Transect_ID,
                                data = herbivory_19_20_recode %>% dplyr::filter(., Transect_ID != "Rural"),
                                family = beta_family(link="logit"))

res <- simulateResiduals(herbivory_urb_usc_m2)
plot(res)


# # main effects:
herbivory_urb_usc_m2_ME <- glmmTMB(Herbivory_mean_Sept ~ (1|Block) + (1|Year) + (1|Population/Family) + Urb_score + Transect_ID,
                                   data = herbivory_19_20_recode %>% dplyr::filter(., Transect_ID != "Rural"),
                                   family = beta_family(link="logit"))

```


# Models for use in analysis
```{r}
# LDMC
ldmc_gr_city_m1
ldmc_gr_usc_m1
ldmc_urbsubs_city_m1
ldmc_urbsubs_usc_m1
```

