---
title: "KSR_2020_analysis"
output: html_document
---

# Statistics: 2020
## comparing lmer w/glmmTMB
```{r}
# # lmer
# lmer_m1 <- lmer(sqrt(Total_Height_June) ~ (1|Block) + (1|Population/Family) + Urb_score,
#   data = heights_both_2020, REML = F)
# 
# car_anova_lmer <- car::Anova(lmer_m1)
# Anova.glmmTMB(lmer_m1, # doesn't run
#               type = "II")
# 
# # glmmTMB
# glmmTMB_m1 <- glmmTMB(sqrt(Total_Height_June) ~ (1|Block) + (1|Population/Family) + Urb_score,
#   data = heights_both_2020,
#   REML = F,
#   family = gaussian)
# 
# car_anova_glmmtmb <- car::Anova(glmmTMB_m1)
# anova_glmmtmb <- Anova.glmmTMB(glmmTMB_m1,
#               type = "II")
# 
# 
# anova_comparison <- bind_rows(tidy(car_anova_lmer),
#           tidy(car_anova_glmmtmb),
#           tidy(anova_glmmtmb)) %>%
#   add_column(Model = c("car::Anova(lmer model)", "car::Anova(glmmTMB model)", "Anova.glmmTMB(glmmTMB model)"), .before = "term") %>%
#   write.csv("comparing_ANOVAs_lmer_glmmtmb.csv")
```

## Export all models & model formulas as a key
```{r}
# list of all models-----
model_list <- list(
  
  flowering_gr_city_m1, # flowering success models
flowering_gr_urb_m1,
flowering_urbsubs_city_m1,
flowering_urbsubs_city_m1_ME,
flowering_urbsubs_usc_m1,
flowering_urbsubs_usc_m1_ME,
  
  Height_Jun20_gr_city_m5, # June height models
Height_Jun20_gr_usc_m2,
Height_Jun20_urbsubs_city_m2,
Height_Jun20_urbsubs_city_m2_ME,
Height_Jun20_urbsubs_usc_m2,
Height_Jun20_urbsubs_usc_m2_ME,
  
    Height_Sept20_gr_city_m2, # Sept height models
Height_Sept20_gr_usc_m5,
Height_Sept20_urbsubs_city_m5,
Height_Sept20_urbsubs_city_m5_ME,
Height_Sept20_urbsubs_usc_m2,
Height_Sept20_urbsubs_usc_m2_ME,
  
    weev_stn_gr_city_m3, # weevil damage (standardized) models
weev_stn_gr_city_m11,
weev_stn_gr_usc_m3,
weev_stn_gr_usc_m12,
weev_stn_urbsubs_city_m4,
weev_stn_urbsubs_city_m4_ME,
weev_stn_urbsubs_city_m11,
weev_stn_urbsubs_city_m11_ME.2,
weev_stn_urbsubs_usc_m4,
weev_stn_urbsubs_usc_m4_ME,
weev_stn_usc_usc_m10,
weev_stn_usc_usc_m10_ME.2,
  
    weev_gr_city_m3, # weevil damage models
weev_gr_city_m11,
weev_gr_usc_m3,
weev_gr_usc_m10,
weev_urbsubs_city_m4,
weev_urbsubs_city_m4_ME, 
weev_urbsubs_city_m11,
weev_urbsubs_city_m11_ME,
weev_urbsubs_usc_m4,
weev_urbsubs_usc_m4_ME,
weev_urbsubs_usc_m11,
weev_urbsubs_usc_m11_ME,
  
  herb2020_gr_dist_m5, # July herbivory models
herb2020_gr_dist_m8,
herb2020_gr_usc_m5,
herb2020_gr_usc_m8,
herb2020_urb_dist_m5,
herb2020_urb_dist_m5_ME,
herb2020_urb_dist_m8,
herb2020_urb_dist_m8_ME,
herb2020_urb_usc_m5,
herb2020_urb_usc_m5_ME,
herb2020_urb_usc_m8,
herb2020_urb_usc_m8_ME,
  
  herb2020.S_gr_dist_m5, # Sept herbivory models
herb2020.S_gr_dist_m12,
herb2020.S_gr_usc_m5,
herb2020.S_gr_usc_m12,
herb2020.S_urb_dist_m5,
herb2020.S_urb_dist_m5_ME,
herb2020.S_urb_dist_m12,
herb2020.S_urb_dist_m12_ME,
herb2020.S_urb_usc_m5,
herb2020.S_urb_usc_m5_ME,
herb2020.S_urb_usc_m12,
herb2020.S_urb_usc_m12_ME,

  rgr_gr_city_m6, # relative growth rate models
rgr_gr_city_m8,
rgr_gr_usc_m6,
rgr_gr_usc_m8,
rgr_urbsubs_city_m5,
rgr_urbsubs_city_m5_ME,
rgr_urbsubs_city_m8,
rgr_urbsubs_city_m8_ME.1,
rgr_urbsubs_usc_m5,
rgr_urbsubs_usc_m5_ME,
rgr_urbsubs_usc_m8,
rgr_urbsubs_usc_m8_ME.1,
  
  rametsJ_gr_city_m2, # June ramets models
rametsJ_gr_usc_m2,
rametsJ_urbsubs_city_m1,
rametsJ_urbsubs_city_m1_ME,
rametsJ_urbsubs_urbsubs_m7,
rametsJ_urbsubs_urbsubs_m7_ME,
  
  rametsS_gr_city_m5, # Sept ramets models
rametsS_gr_usc_m5,
rametsS_urbsubs_city_m5,
rametsS_urbsubs_city_m5_ME,
rametsS_urbsubs_usc_m5,
rametsS_urbsubs_usc_m5_ME,

  surv20_gr_city_m1, # survival models
surv20_gr_usc_m1,
surv20_urbsubs_city_m1,
surv20_urbsubs_city_m1_ME,
surv20_urbsubs_usc_m1,
surv20_urbsubs_usc_m1_ME
  
)

# list of all models, in quotes-----
all_models_2020 <- qq(
  flowering_gr_city_m1, # flowering success models
flowering_gr_urb_m1,
flowering_urbsubs_city_m1,
flowering_urbsubs_city_m1_ME,
flowering_urbsubs_usc_m1,
flowering_urbsubs_usc_m1_ME,
  
  Height_Jun20_gr_city_m5, # June height models
Height_Jun20_gr_usc_m2,
Height_Jun20_urbsubs_city_m2,
Height_Jun20_urbsubs_city_m2_ME,
Height_Jun20_urbsubs_usc_m2,
Height_Jun20_urbsubs_usc_m2_ME,
  
    Height_Sept20_gr_city_m2, # Sept height models
Height_Sept20_gr_usc_m5,
Height_Sept20_urbsubs_city_m5,
Height_Sept20_urbsubs_city_m5_ME,
Height_Sept20_urbsubs_usc_m2,
Height_Sept20_urbsubs_usc_m2_ME,
  
    weev_stn_gr_city_m3, # weevil damage (standardized) models
weev_stn_gr_city_m11,
weev_stn_gr_usc_m3,
weev_stn_gr_usc_m12,
weev_stn_urbsubs_city_m4,
weev_stn_urbsubs_city_m4_ME,
weev_stn_urbsubs_city_m11,
weev_stn_urbsubs_city_m11_ME.2,
weev_stn_urbsubs_usc_m4,
weev_stn_urbsubs_usc_m4_ME,
weev_stn_usc_usc_m10,
weev_stn_usc_usc_m10_ME.2,
  
    weev_gr_city_m3, # weevil damage models
weev_gr_city_m11,
weev_gr_usc_m3,
weev_gr_usc_m10,
weev_urbsubs_city_m4,
weev_urbsubs_city_m4_ME, 
weev_urbsubs_city_m11,
weev_urbsubs_city_m11_ME,
weev_urbsubs_usc_m4,
weev_urbsubs_usc_m4_ME,
weev_urbsubs_usc_m11,
weev_urbsubs_usc_m11_ME,
  
  herb2020_gr_dist_m5, # July herbivory models
herb2020_gr_dist_m8,
herb2020_gr_usc_m5,
herb2020_gr_usc_m8,
herb2020_urb_dist_m5,
herb2020_urb_dist_m5_ME,
herb2020_urb_dist_m8,
herb2020_urb_dist_m8_ME,
herb2020_urb_usc_m5,
herb2020_urb_usc_m5_ME,
herb2020_urb_usc_m8,
herb2020_urb_usc_m8_ME,
  
  herb2020.S_gr_dist_m5, # Sept herbivory models
herb2020.S_gr_dist_m12,
herb2020.S_gr_usc_m5,
herb2020.S_gr_usc_m12,
herb2020.S_urb_dist_m5,
herb2020.S_urb_dist_m5_ME,
herb2020.S_urb_dist_m12,
herb2020.S_urb_dist_m12_ME,
herb2020.S_urb_usc_m5,
herb2020.S_urb_usc_m5_ME,
herb2020.S_urb_usc_m12,
herb2020.S_urb_usc_m12_ME,

  rgr_gr_city_m6, # relative growth rate models
rgr_gr_city_m8,
rgr_gr_usc_m6,
rgr_gr_usc_m8,
rgr_urbsubs_city_m5,
rgr_urbsubs_city_m5_ME,
rgr_urbsubs_city_m8,
rgr_urbsubs_city_m8_ME.1,
rgr_urbsubs_usc_m5,
rgr_urbsubs_usc_m5_ME,
rgr_urbsubs_usc_m8,
rgr_urbsubs_usc_m8_ME.1,
  
  rametsJ_gr_city_m2, # June ramets models
rametsJ_gr_usc_m2,
rametsJ_urbsubs_city_m1,
rametsJ_urbsubs_city_m1_ME,
rametsJ_urbsubs_urbsubs_m7,
rametsJ_urbsubs_urbsubs_m7_ME,
  
  rametsS_gr_city_m5, # Sept ramets models
rametsS_gr_usc_m5,
rametsS_urbsubs_city_m5,
rametsS_urbsubs_city_m5_ME,
rametsS_urbsubs_usc_m5,
rametsS_urbsubs_usc_m5_ME,

  surv20_gr_city_m1, # survival models
surv20_gr_usc_m1,
surv20_urbsubs_city_m1,
surv20_urbsubs_city_m1_ME,
surv20_urbsubs_usc_m1,
surv20_urbsubs_usc_m1_ME)


# get model formulas --> export -----

# make list of model summaries
# summaries <- lapply(model_list, summary)
# summaries_table1 <- sjPlot::tab_model(model_list,
#                                       auto.label = FALSE,
#                                       show.ci = FALSE)



all_models_2020_formulas <- lapply(model_list, formula) %>%
  lapply(., toString) %>%
  as.character()

# get df with model name and formula
modsum_1 <- data.frame(Model_Name1 = all_models_2020, 
       Formula = all_models_2020_formulas)
       # sapply(list1, r.squaredGLMM()[1]))

# get df with model family and formula 
modsum_2 <- tibble(Model_Name1 = all_models_2020,
                   col2 = lapply(model_list, family),
               Family = sub("\\,.*", "", col2)) %>%
   dplyr::select(-col2) %>%
  mutate(Family = str_remove(Family, "list"))
 
# modsum_2 <- tibble(lapply(list1, family)) %>%
#   t() %>%
#   as.data.frame() %>%
#   dplyr::select(., c(V7, V15)) %>%
#   unlist() %>%
#     as.data.frame()




# merge the two dfs
modsum_merge2 <- inner_join(modsum_1, modsum_2, by = "Model_Name1") 
# %>%
#   write.csv(here::here("./Figures_Tables/ANOVA_tables_images/Model_List.csv"))
# 
# # Get R-sq values here
# capture.output(lapply(model_list, r.squaredGLMM), file = here::here("./Figures_Tables/ANOVA_tables_images/Model_R_squared_values.csv"))


# library(jtools)
# export_summs(model_list, digits = 3, to.file = "xlsx", file.name = here::here("./Figures_Tables/ANOVA_tables_images/R_sq_2020.xlsx"))




# these models have at least one significant effect:-----
model_list_sig <- modsum_merge2[c(7,13,
                                 # 25, # full model with a significantly higher AIC than its reduced version, So get rid of it
        26,37,38,41,42,47,48,49,50,51,52,55,71,72,74,77,83,84,85,87,88),] %>%
  dplyr::pull(., Model_Name1)




# these models had city_dist as a significant main effect:
model_list_sig.citydist <- modsum_merge2[c(7,13,47:50,55,71,72,74,85,87:88),] %>%
  dplyr::pull(., Model_Name1)

# these models had Urb_score as a significant main effect:
model_list_sig.urbscore <- modsum_merge2[c(51:52, 83:84),] %>%
  dplyr::pull(., Model_Name1)

# these models had Transect_ID as a significant main effect:
model_list_sig.transect <- modsum_merge2[c(26, 37:38, 41:42, 74, 83:84),] %>%
  dplyr::pull(., Model_Name1) # got rid of 25

# this model had its interaction as the significant main effect:
model_list_sig.interaxn <- model_list_sig[77]



# Export table w/model summaries-----
tidy_sb <- function(model){
  
  return(
    car::Anova(model) %>%
      tidy() %>%
      as.data.frame() %>%
      dplyr::mutate(Response = as.character(formula(model)[2]),
                    .before = term) %>%
      # dplyr::mutate(Model = paste(n(model)),
      #               .before = term) %>%
      dplyr::mutate(Sites = case_when(
        str_detect(as.character(formula(model)[3]), "Transect_ID") == TRUE ~ "Urban Only",
        str_detect(as.character(formula(model)[3]), "Transect_ID") == FALSE ~ "All"),
                    .before = term) %>%
      dplyr::mutate(Significance = case_when(p.value < 0.001 ~ "***",
                                             p.value < 0.01 ~ "**",
                                             p.value <= 0.05 ~ "*", 
                                             p.value <= 0.1 ~ "Marginal")) %>%
      dplyr::mutate(., AIC = AIC(model)) %>%
      dplyr::select(., -df) %>%
      dplyr::rename(., Chi_sq = statistic,
                    Predictor = term,
                    p = p.value) %>%
      dplyr::mutate_if(.,
                is.character,
                str_replace_all,
                pattern = c("City_dist"),
                replacement = c("Distance to City Center")) %>%
        dplyr::mutate_if(.,
                is.character,
                str_replace_all,
                pattern = c("Urb_score"),
                replacement = c("Urbanization Score")) %>%
        dplyr::mutate_if(.,
                is.character,
                str_replace_all,
                pattern = c("Transect_ID"),
                replacement = c("Subtransect")) %>%
      mutate_if(is.numeric, round, 3))
  }


test1 <- do.call(rbind, lapply(model_list, tidy_sb))
test2 <- test1 %>%
      dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("Flowered2020"),
            replacement = c("Flowering Success")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("sqrt(Total_Height_June)"),
            replacement = c("Height (June)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("sqrt(Total_Height_Sept)"),
            replacement = c("Height (Sept)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = "(Herbivory.July_mean_binary)",
            replacement = "Herbivory (July) (Binary)") %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("(Herbivory.Sept_mean_binary)"),
            replacement = c("Herbivory (Sept) (Binary)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("(rel_growth_rate_binary)"),
            replacement = c("Relative growth rate (Binary)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("(scar_div_Juneheight_binary)"),
            replacement = c("Weevil scar length (per cm height) (Binary)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("(scar_length_cm_binary)"),
            replacement = c("Weevil scar length (Binary)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("dead_2020"),
            replacement = c("Survival")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("log(Herbivory.July_mean)"),
            replacement = c("Herbivory (July)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("log(Herbivory.Sept_mean)"),
            replacement = c("Herbivory (Sept)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("log(scar_div_Juneheight)"),
            replacement = c("Weevil scar length (per cm height)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("log(Scar_length_cm + 0.1)"),
            replacement = c("Weevil scar length")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("Ramets_June"),
            replacement = c("No. Ramets (June)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("Ramets_Sept"),
            replacement = c("No. Ramets (Sept)")) %>%
  dplyr::mutate_if(.,
            is.character,
            str_replace_all,
            pattern = c("sqrt(rel_growth_rate)"),
            replacement = c("Relative growth rate")) 

test2.q1 <- test2 %>% filter(Sites == "All")
test2.q2 <- test2 %>% filter(Sites == "Urban Only") %>%
  dcast(.,  Response + Chi_sq + p + Predictor ~ Predictor , value.var = "AIC")


write.csv(test1,  here::here("./Figures_Tables/ANOVA_tables_images/model_summaries.csv"))
```

## Find change in var estimates along gradient/across subtransects
### Change along gradient: Entire gradient models
```{r}

# code outside of function -----
intercept1 <- fixef(rametsS_gr_city_m5)$cond[1] %>%
  as.numeric() # gives intercept for city_dist = 0.71385548
slope1 <- fixef(rametsS_gr_city_m5)$cond[2] %>%
  as.numeric() # gives slope for city_dist = 0.002606745
urban_terminus = 3.5 # km; most urban pop is close to this distance
rural_terminus = 67 # km; most rural pop is close to this distance
midpoint = 35.25 # km; midpoint of urban and rural terminii
# y = mx + b

# y(urban terminus)
urban_estimate <- slope1 * urban_terminus + intercept1  %T>%
  print()
paste(noquote(c("There are an average of", round(urban_estimate, 3), "ramets/plant in Sept at the urban terminus")), collapse = ' ')

# y(rural terminus)
rural_estimate <- slope1 * rural_terminus + intercept1 %T>%
  print()
paste(noquote(c("There are an average of", round(rural_estimate, 3), "ramets/plant in Sept at the rural terminus")), collapse = ' ')

# AVG NUM. OF RAMETS FROM URBAN TO RURAL TERMINUS:
avg_diff <- (  urban_estimate - rural_estimate )  /     (0.5*       (  urban_estimate + rural_estimate  )  ) %T>%
  print()

# % CHANGE
percent_change <- (((rural_estimate - urban_estimate) / urban_estimate) * 100) %T>%
  print()
paste(noquote(c("On average, the most rural plants produced", round(percent_change, 1), "% more ramets/plant in Sept than the most urban plants")), collapse = ' ')



# Function -----
Perc_change_gradient <- function(city_dist_model){

  urban_terminus = 3.5 # km; most urban pop is close to this distance
  rural_terminus = 67 # km; most rural pop is close to this distance
  midpoint = 35.25 # km; midpoint of urban and rural terminii

  intercept1 <- fixef(city_dist_model)$cond[1] %>%
  as.numeric() # gives intercept for city_dist
  
  slope1 <- fixef(city_dist_model)$cond[2] %>%
  as.numeric() # gives slope for city_dist
  
  response_var <- names(city_dist_model$modelInfo$respCol) %>%
    str_remove(., "[()]")
      

# y(urban terminus)
  urban_estimate <- slope1 * urban_terminus + intercept1 #  %T>%
  # print()
  
  print(paste(noquote(c("There are an average of", round(urban_estimate, 3), response_var, "per plant at the urban terminus")), collapse = ' '))

# y(rural terminus)
   rural_estimate <- slope1 * rural_terminus + intercept1 # %T>%
  # print()
  
  print(paste(noquote(c("There are an average of", round(rural_estimate, 3), response_var, "per plant at the rural terminus")), collapse = ' '))

# AVG NUM. OF RAMETS FROM URBAN TO RURAL TERMINUS:
  avg_diff <- abs( urban_estimate - rural_estimate )  / (0.5* (    urban_estimate + rural_estimate  )  ) # %T>%
  # print()

# % CHANGE
  percent_change <- (((rural_estimate - urban_estimate) / abs(urban_estimate)) * 100) # %T>%
  # print()
  
  print(paste(noquote(c("On average, the most rural plants produced", round(percent_change, 1), "% more", response_var, " per plant than the most urban plants")), collapse = ' '))

}

## for the models that don't work with the original function, try this:
Perc_change_gradient.2 <- function(city_dist_model){

  urban_terminus = 3.5 # km; most urban pop is close to this distance
  rural_terminus = 67 # km; most rural pop is close to this distance
  midpoint = 35.25 # km; midpoint of urban and rural terminii

  intercept1 <- fixef(city_dist_model)[1] %>%
  as.numeric() # gives intercept for city_dist
  
  slope1 <- fixef(city_dist_model)[2] %>%
  as.numeric() # gives slope for city_dist
  
  response_var <- names(city_dist_model@frame)[1] 
      

# y(urban terminus)
  urban_estimate <- slope1 * urban_terminus + intercept1 #  %T>%
  # print()
  
  print(paste(noquote(c("There are an average of", round(urban_estimate, 3), response_var, "per plant at the urban terminus")), collapse = ' '))

# y(rural terminus)
   rural_estimate <- slope1 * rural_terminus + intercept1 # %T>%
  # print()
  
  print(paste(noquote(c("There are an average of", round(rural_estimate, 3), response_var, "per plant at the rural terminus")), collapse = ' '))

# AVG NUM. OF RAMETS FROM URBAN TO RURAL TERMINUS:
  avg_diff <- abs( urban_estimate - rural_estimate )  / (0.5* (    urban_estimate + rural_estimate  )  ) # %T>%
  # print()

# % CHANGE
  percent_change <- (((rural_estimate - urban_estimate) / abs(urban_estimate)) * 100) # %T>%
  # print()
  
  print(paste(noquote(c("On average, the most rural plants produced", round(percent_change, 1), "% more", response_var, " per plant than the most urban plants")), collapse = ' '))

}

## can't get these automated functions to work so I'll do this manually...
# lapply(as.name(model_list_sig), Perc_change_gradient)
# 
# for (model in model_list_sig) {
#   Perc_change_gradient(as.numeric(model))
# }


Perc_change_gradient  (  Height_Jun20_gr_city_m5          )
Perc_change_gradient.2(  Height_Sept20_gr_city_m2         )
Perc_change_gradient  (  rametsS_gr_city_m5               )

# these are binary so this type of analysis doesn't make sense...
# Perc_change_gradient.2(  herb2020.S_gr_dist_m5            )
```

### Change along gradient: Just urban sites models
```{r}
# Function -----
Perc_change_gradient.urbansites <- function(city_dist_model){

  urban_terminus = 3.5 # km; most urban pop is close to this distance
  rural_terminus =  32 # km; most rural pop is close to this distance

  intercept1 <- fixef(city_dist_model)$cond[1] %>%
  as.numeric() # gives intercept for city_dist
  
  slope1 <- fixef(city_dist_model)$cond[2] %>%
  as.numeric() # gives slope for city_dist
  
  response_var <- names(city_dist_model$modelInfo$respCol) %>%
    str_remove(., "[()]")
      

# y(urban terminus)
  urban_estimate <- slope1 * urban_terminus + intercept1 #  %T>%
  # print()
  
  print(paste(noquote(c("There are an average of", round(urban_estimate, 3), response_var, "per plant at the urban terminus")), collapse = ' '))

# y(rural terminus)
   rural_estimate <- slope1 * rural_terminus + intercept1 # %T>%
  # print()
  
  print(paste(noquote(c("There are an average of", round(rural_estimate, 3), response_var, "per plant at the rural terminus")), collapse = ' '))

# AVG NUM. OF RAMETS FROM URBAN TO RURAL TERMINUS:
  avg_diff <- abs( urban_estimate - rural_estimate )  / (0.5* (    urban_estimate + rural_estimate  )  ) # %T>%
  # print()

# % CHANGE
  percent_change <- (((rural_estimate - urban_estimate) / abs(urban_estimate)) * 100) # %T>%
  # print()
  
  print(paste(noquote(c("On average, the most rural plants produced", round(percent_change, 1), "% more", response_var, " per plant than the most urban plants")), collapse = ' '))
  
  # AVG NUM. OF RAMETS FROM RURAL TO URBAN TERMINUS:
  avg_diff.1 <- abs( rural_estimate - urban_estimate )  / (0.5* (    urban_estimate + rural_estimate  )  ) # %T>%
  # print()

# % CHANGE
  percent_change.1 <- (((urban_estimate - rural_estimate ) / abs(rural_estimate)) * 100) # %T>%
  # print()
  
  print(paste(noquote(c("On average, the most urban plants produced", round(percent_change.1, 1), "% more", response_var, " per plant than the most rural plants")), collapse = ' '))

}

## for the models that don't work with the original function, try this:
Perc_change_gradient.2.urbansites <- function(city_dist_model){

  urban_terminus = 3.5 # km; most urban pop is close to this distance
  rural_terminus =  32 # km; most rural pop is close to this distance

  intercept1 <- fixef(city_dist_model)[1] %>%
  as.numeric() # gives intercept for city_dist
  
  slope1 <- fixef(city_dist_model)[2] %>%
  as.numeric() # gives slope for city_dist
  
  response_var <- names(city_dist_model@frame)[1] 
      

# y(urban terminus)
  urban_estimate <- slope1 * urban_terminus + intercept1 #  %T>%
  # print()
  
  print(paste(noquote(c("There are an average of", round(urban_estimate, 3), response_var, "per plant at the urban terminus")), collapse = ' '))

# y(rural terminus)
   rural_estimate <- slope1 * rural_terminus + intercept1 # %T>%
  # print()
  
  print(paste(noquote(c("There are an average of", round(rural_estimate, 3), response_var, "per plant at the rural terminus")), collapse = ' '))

# AVG NUM. OF RAMETS FROM URBAN TO RURAL TERMINUS:
  avg_diff <- abs( urban_estimate - rural_estimate )  / (0.5* (    urban_estimate + rural_estimate  )  ) # %T>%
  # print()

# % CHANGE
  percent_change <- (((rural_estimate - urban_estimate) / abs(urban_estimate)) * 100) # %T>%
  # print()
  
  print(paste(noquote(c("On average, the most rural plants produced", round(percent_change, 1), "% more", response_var, " per plant than the most urban plants")), collapse = ' '))
  
  # AVG NUM. OF RAMETS FROM RURAL TO URBAN TERMINUS:
  avg_diff.1 <- abs( rural_estimate - urban_estimate )  / (0.5* (    urban_estimate + rural_estimate  )  ) # %T>%
  # print()

# % CHANGE
  percent_change.1 <- (((urban_estimate - rural_estimate ) / abs(rural_estimate)) * 100) # %T>%
  # print()
  
  print(paste(noquote(c("On average, the most urban plants produced", round(percent_change.1, 1), "% more", response_var, " per plant than the most rural plants")), collapse = ' '))
  
}


Perc_change_gradient.urbansites  (  herb2020_urb_dist_m8             )
Perc_change_gradient.urbansites  (  herb2020_urb_dist_m8_ME          )
AIC(herb2020_urb_dist_m8, herb2020_urb_dist_m8_ME) # not sig diff but ME has lower AIC. Use it in report.

Perc_change_gradient.urbansites  (  rgr_urbsubs_city_m8_ME.1         )

Perc_change_gradient.urbansites  (  rametsS_urbsubs_city_m5          )
Perc_change_gradient.urbansites  (  rametsS_urbsubs_city_m5_ME       )
AIC(rametsS_urbsubs_city_m5, rametsS_urbsubs_city_m5_ME) # not sig diff but ME has lower AIC. Use it in report.

# these are binary so this type of analysis doesn't make sense...
# Perc_change_gradient.2.urbansites(  herb2020_urb_dist_m5             )
# Perc_change_gradient.2.urbansites(  herb2020_urb_dist_m5_ME          )
AIC(herb2020_urb_dist_m5, herb2020_urb_dist_m5_ME) # not sig diff but ME has lower AIC. Use it in report.

# Perc_change_gradient.2.urbansites(  rgr_urbsubs_city_m5              )
# Perc_change_gradient.2.urbansites(  rgr_urbsubs_city_m5_ME           )
AIC(rgr_urbsubs_city_m5, rgr_urbsubs_city_m5_ME) # not sig diff but ME has lower AIC. Use it in report. DIDN'T PUT IN COMM MTG REPORT- NOT SURE HOW TO INTEGRATE IT/REPORT IT

```

### Difference between urban subtransects models
```{r}

# code outside of function -----
# summary(weev_urbsubs_city_m11)
# car::Anova(weev_urbsubs_city_m11)
# 
# intercept2 <- (fixef(weev_urbsubs_city_m11)$cond[3] * 100) %>%
#   as.numeric() %T>%
#   print() # gives estimate of difference btwn 2 subs
# paste(noquote(c("On average, plants from the corridor subtransect experienced", round(intercept2, 1), "% more weevil damage than plants from the non-corridor subtransect")), collapse = ' ')


# Function -----
Perc_change_subtransects <- function(urban_model) {
  
    response_var <- names(urban_model$modelInfo$respCol) %>%
    str_remove(., "[()]")
    
    intercept2 <- (fixef(urban_model)$cond[3] * 100) %>%
  as.numeric() # %T>% print() # gives estimate of difference btwn 2 subs
    
    print(paste(noquote(c("On average, plants from the corridor subtransect experienced", round(intercept2, 1), "% more ", response_var, "than plants from the non-corridor subtransect")), collapse = ' '))

}


Perc_change_subtransects(  weev_stn_urbsubs_city_m11_ME.2 ) 

Perc_change_subtransects(  weev_urbsubs_city_m11          )
Perc_change_subtransects(  weev_urbsubs_city_m11_ME       ) 
AIC(weev_urbsubs_city_m11, weev_urbsubs_city_m11_ME ) # not sig diff but ME has lower AIC. Use it in report.

Perc_change_subtransects(  weev_urbsubs_usc_m11           )
Perc_change_subtransects(  weev_urbsubs_usc_m11_ME        )
AIC(weev_urbsubs_usc_m11, weev_urbsubs_usc_m11_ME ) # not sig diff but ME has lower AIC. Use it in report.
## NOT REPORTING THIS IN COMM MTG REPORT- URB SCORE (though very close to city_dist- a good sign)

Perc_change_subtransects(  rametsJ_urbsubs_urbsubs_m7     )
Perc_change_subtransects(  rametsJ_urbsubs_urbsubs_m7_ME  )
AIC(rametsJ_urbsubs_urbsubs_m7, rametsJ_urbsubs_urbsubs_m7_ME ) # not sig diff but ME has lower AIC. Use it in report.
## NOT REPORTING THIS IN COMM MTG REPORT- URB SCORE.

Perc_change_subtransects(  rgr_urbsubs_city_m8_ME.1       )

```

