# Set up notebook
## Load libraries & functions
```{r}
source("libraries.R")
source("functions.R")
```

## Import representative figures
```{r}
source(knitr::purl("scripts/Create_regression_figs/1yr_mods/Figures_growth.Rmd", quiet=TRUE))

source(knitr::purl("scripts/Create_regression_figs/1yr_mods/Figures_defense.Rmd", quiet=TRUE))

source(knitr::purl("scripts/Create_regression_figs/1yr_mods/Figures_Reproductive.Rmd", quiet=TRUE))

source(knitr::purl("scripts/Create_regression_figs/1yr_mods/Figures_herbivores_2021.Rmd", quiet=TRUE))
```

# Combine plots into one figure
## Gradient / City_dist
```{r}

ggarrange(
  addborder(ggpred_Q1.citydist_weev_bin, "defense"),
  addborder(ggpred_Q1.citydist_firstpods, "reproduction"),
  addborder(ggpred_Q1.citydist_asclepiadis, "herbivores"),
  addborder(ggpred_Q1.citydist_height_e, "growth") +
            font("x.text"),
          ncol = 2,
          nrow = 2,
          align = "hv",
          labels = list("A", "B", "C", "D"),
          font.label = (size =16),
          common.legend = T,
          legend = "top") %T>%
  plot

dev.copy2pdf(file = here::here("./Figures_Tables/Regressions/1yr_mods/Q1_grad_citydist_representative_panels.pdf"),
             width = 10, height = 8)
```


## Gradient / Urbanization Score
```{r}
ggarrange(
  addborder(ggpred_Q1.urbscore_weev_bin, "defense"),
  addborder(ggpred_Q1.urbscore_firstpods, "reproduction"),
  addborder(ggpred_Q1.usc_asclepiadis, "herbivores"),
  addborder(ggpred_Q1.urbscore_height_e, "growth") +
            font("x.text"),
          ncol = 2,
          nrow = 2,
          align = "hv",
          labels = list("A", "B", "C", "D"),
          font.label = (size =16),
          common.legend = T,
          legend = "top") %T>%
  plot


dev.copy2pdf(file = here::here("./Figures_Tables/Regressions/1yr_mods/Q1_grad_urbscore_representative_panels.pdf"),
             width = 10, height = 8)
```

## Urb Subtransects / City_dist
```{r}
ggarrange(
  addborder(ggpred_Q2.citydist_weev_bin, "defense"),
  addborder(ggpred_Q2.citydist_firstpods, "reproduction"),
  addborder(ggpred_Q2.citydist_asclepiadis, "herbivores"),
  addborder(ggpred_Q2.citydist_height_e, "growth") +
            font("x.text"),
          ncol = 2,
          nrow = 2,
          align = "hv",
          labels = list("A", "B", "C", "D"),
          font.label = (size =16),
          common.legend = T,
          legend = "top") %T>%
  plot

dev.copy2pdf(file = here::here("./Figures_Tables/Regressions/1yr_mods/Q2_urbsubs_citydist_representative_panels.pdf"),
             width = 10, height = 8)
```


## Urb Subtransects / Urbanization Score
```{r}
ggarrange(
  addborder(ggpred_Q2.urbsubs_weev_bin, "defense"),
  addborder(ggpred_Q2.urbscore_firstpods, "reproduction"),
  addborder(ggpred_Q2.usc_asclepiadis, "herbivores"),
  addborder(ggpred_Q2.urbsubs_height_e, "growth") +
            font("x.text"),
          ncol = 2,
          nrow = 2,
          align = "hv",
          labels = list("A", "B", "C", "D"),
          font.label = (size =16),
          common.legend = T,
          legend = "top") %T>%
  plot

dev.copy2pdf(file = here::here("./Figures_Tables/Regressions/1yr_mods/Q2_urbsubs_urbscore_representative_panels.pdf"),
             width = 10, height = 8)
```
