---
title: "KSR_2019_Height_Survival_Analysis1"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

# 1.1 Load packages

```{r}
library(dplyr)

```

# 1.2 Import data

```{r, import}
Data <- read.table("~/R_Projects/CommonGardenExperiment_2019Data/DataAnalysis_FirstHeightSurvivalMeasurement_20190610.csv", na.strings=c("NO PLANT", "none"), blank.lines.skip=TRUE, header=TRUE, sep=",")
# head(Data, 20)
```

# 1.2 Remove rows without plants, empty columns

```{r}
b <- is.na(Data$Block) == TRUE
b2 <- c(1:nrow(Data))[b]
Data <- Data[-b2,]
Data <- Data[,-(29:35)]
names(Data)[1]<-"Row"
```


# 1.3 Make certain columns factors

```{r message=FALSE, warning=FALSE}

Data$Block <- factor(Data$Block)
Data$Population <- factor(Data$Population)
Data$Family <- factor(Data$Family)
Data$Replicate <- factor(Data$Replicate)
#str(Data)
```


# 1.4 Survival table intermediates

```{r message=FALSE, warning=FALSE}
Survival_by_fam <- Data %>% group_by(Population, Family) %>%
   count(Dead)
  
# Survival_by_fam


Survival_by_pop <- Data %>% group_by(Population) %>%
   count(Dead)

# Survival_by_pop

```

# 1.5 Reshape data frame

```{r}
library(reshape)
library(reshape2)
cols <- c(4,5,11)

melt_data <- Data[,cols]
# long <- melt(Survival_by_fam, id.vars = c("Population", "Family"))
# final <- dcast(long, Population + Family ~ variable, sum)

# melt_surv <- melt(melt_data, id=(c("Population","Family")))
# cast_surv <- cast(melt_data, "Population"+"Family")
# # aggregate(Data$Dead, by=list(Population=Data$Population), FUN=count())

# alive <- filter(Survival, Dead == "no")

# tab1 <- table(Survival_by_fam$Population,Survival_by_fam$Family, Survival_by_fam$Dead)
# tab2 <- as.data.frame(tab1)
# names(tab2)[1]<-"Population"
# names(tab2)[2]<-"Family"
# names(tab2)[3]<-"Dead"

tab1 <- table(Data$Population,Data$Family, Data$Dead)
tab2 <- as.data.frame(tab1)
names(tab2)[1]<-"Population"
names(tab2)[2]<-"Family"
names(tab2)[3]<-"Dead"
# tab2$Percent <- NA

# long <- melt(tab2, id.vars = c("Population", "Family"))
# final <- dcast(long, Population + Family ~ value , sum)

library(dplyr)
library(tidyr)

a <- spread(tab2, Dead, Freq)

```

# 1.6 Edit table

```{r}
a$Total <- NA
names(a)[5] <- "nothing_there"
a$Total <- rowSums(a[3:5])

a$maybe <- as.numeric(a$maybe)
a$no <- as.numeric(a$no)
a$nothing_there <- as.numeric(a$nothing_there)

a<-a[!(a$Total==0),] # removing rows corresponding to populations' a priori empty families

```


# 1.7 Find probable, definite survival percentages per family

```{r}

a$Pct_Survival_Definite <- NA
a$Pct_Survival_Definite <- a$no/a$Total # definite survival assumes none of "maybe" milkweed survive
a$Pct_Survival_Definite <- signif(a$Pct_Survival_Definite, 2)*100

a$Pct_Survival_Probably <- NA
a$Pct_Survival_Probably <- (a$no + 0.5*a$maybe)/a$Total  # probable survival assumes half of "maybe" milkweed survive
a$Pct_Survival_Probably <- signif(a$Pct_Survival_Probably, 2)*100

a

```


# 1.8 Find probable, definite survival percentages per population

```{r}
# d <- a %>% group_by(Population) %>% summarise(mean_no = mean(no),
#                                               mean_maybe = mean(maybe),
#                                               mean_nothingthere = mean(nothing_there),
#                                               mean_total = mean(Total))

e <- a %>% group_by(Population) %>% summarise(sum_no = sum(no),
                                              sum_maybe = sum(maybe),
                                              sum_nothingthere = sum(nothing_there),
                                              sum_total = sum(Total))

e$Pct_Survival_Definite <- NA
e$Pct_Survival_Definite <- e$sum_no/e$sum_total # definite survival assumes none of "maybe" milkweed survive
e$Pct_Survival_Definite <- signif(e$Pct_Survival_Definite, 2)*100

e$Pct_Survival_Probably <- NA
e$Pct_Survival_Probably <- (e$sum_no + 0.5*e$sum_maybe)/e$sum_total # probable survival assumes half of "maybe" milkweed survive
e$Pct_Survival_Probably <- signif(e$Pct_Survival_Probably, 2)*100

e


f <- as.data.frame(table(Data$Dead)) # total plants for each mortality status
names(f)[1]<-"Dead?"
names(f)[2]<-"Count"
f[1,2] + f[2,2] + f[3,2] # Total plants

f
```

