---
title: "Reproductive Trait Analysis"
author: "Sophie Breitbart"
output:
  html_document:
    number_sections: true
    df_print: paged
    toc: yes
    toc_depth: 6
    toc_float:
      collapsed: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
editor_options: 
  chunk_output_type: console
NOTES:
  -Still to do--
    -try to do an RDA (or PCA?) with all the traits
    -make a ReadMe file for each level
    -calculate heritability coefficients
# WHEN TOTALLY DONE, type this:
# renv::activate()
# renv::snapshot()
---

NOTES:

+-----------------------------+-----------+-----------+-----------+
| Trait                       | 2019 Data | 2020 Data | 2021 Data |
+=============================+:=========:+:=========:+:=========:+
| All reproductive traits     |           | X         | X         |
+-----------------------------+-----------+-----------+-----------+


# Set up notebook
## Load libraries and add functions
```{r}
source("libraries.R")
source("functions.R")
```

## Import data
```{r}
# 2020 data-----
reproductive_2020 <- read.csv(here::here("./CommonGardenExperiment_2020Data/clean_data/2020_reproductive_clean.csv")) %>%
  dplyr::select(., -c(1:2))

flowering_2020 <- read.csv(here::here("./CommonGardenExperiment_2020Data/clean_data/2020_floweringplants_clean.csv")) %>%
  dplyr::select(., -c(1:2))

  
# 2021 data
reproductive_2021 <- read.csv(here::here("./CommonGardenExperiment_2021Data/clean_data/2021_reproductive_clean.csv")) %>%
  dplyr::select(., -1)

flowering_2021 <- read.csv(here::here("./CommonGardenExperiment_2021Data/clean_data/2021_floweringplants_clean.csv")) %>%
  dplyr::select(-1)
```


## MAKE DIAGNOSTIC RMD NEXT, THEN FIGURE OUT HOW TO STRUCTURE REST OF THIS

